#!/bin/bash
set -e
export PATH=$PATH:/var/vcap/packages/jre/jre1.8.0_73/bin
sh /var/vcap/packages/kafka/kafka_2.11-0.9.0.1/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --zookeeper $1 --topic $2 
